### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by laulaz** [zopefoundation/z3c.jbot#14]
Would it be possible to make a new release of this package ? or give me the right to do it myself on Pypi (user: laz) ?

@malthe maybe ?

Thanks a lot !

**Comment by icemac** [comment]
@laulaz According to https://pypi.org/project/z3c.jbot/ you are now a maintainer of this package on PyPI.

**Comment by laulaz** [comment]
@icemac I made the release (it's on Pypi), but then realised that I have no rights to push release commits on this repo.
Can you give me the rights to do so ?

Thank you !

**Comment by malthe** [comment]
@laulaz I think you have to become a contributor to the organization for that? Isn't that how it works. I don't really know, I think I signed a contributor agreement at some point.

**Comment by laulaz** [comment]
@malthe I've signed the Plone contributor's agreement years ago ... which should cover both : https://plone.org/foundation/contributors-agreement

**Comment by malthe** [comment]
@laulaz seems like it should have happened automatically then; I have tried to find more information but I think you're best bet is to write agreements@plone.org and ask why you haven't been added as a developer to the [zopefoundation](https://github.com/zopefoundation/) organization.

**Comment by laulaz** [comment]
Done, rights obtained, code pushed 👍
