### ISSUE TITLE
Tests fail: unregistration is broken

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/z3c.jbot#4]
There's [one test failure](https://travis-ci.org/zopefoundation/z3c.jbot/builds/91771791) in master:

```
Failure in test /home/mg/src/zopefoundation/z3c.jbot/src/z3c/jbot/README.txt
Failed doctest test for README.txt
  File "/home/mg/src/zopefoundation/z3c.jbot/src/z3c/jbot/README.txt", line 0

----------------------------------------------------------------------
File "/home/mg/src/zopefoundation/z3c.jbot/src/z3c/jbot/README.txt", line 140, in README.txt
Failed example:
    view.template()
Expected:
    u'This is an example page template.\n'
Got:
    u'Override from ./request.\n'

```

AFAICS what the test does is
- register an override for this template
- render it, expecting the overridden template
- remove the override
- render it, expecting the original template

The last step fails.

**Comment by jensens** [comment]
this in no longer a problem on non-windows systems. for further discussion see #8
